# Setup
title:        Cytoflow
tagline:      Better quantitative flow cytometry.
version:      1.2.3
baseurl:      "/"
paginate:     1

# About/contact
author:  
  name:       Brian Teague
  url:        https://teague.bio

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
